export const UserMapper = {
  map: (value: any) => ({
    _id: value.user_id ? value.user_id : '',
    firstName: value.first_name ? value.first_name : '',
    lastName: value.last_name ? value.last_name : '',
    birthday: value.birthday ? value.birthday : '',
    emailAddress: value.mail ? value.mail : '',
    phoneNumber: value.contact_phone ? value.contact_phone : '',
    password: value.password ? value.password : '',
    acceptPolicy: value.acceptPolicy ? value.acceptPolicy : '',
    address: value.address1 ? value.address1 : '',
    city: value.city ? value.city : '',
    state: value.state ? value.state : '',
    countryName: value.country_name ? value.country_name : '',
    postCode: value.post_code ? value.post_code : '',
    mfaSetting: value.mfa_setting ? value.mfa_setting : '',
    otpBase32: value.otpBase32 ? value.otpBase32 : '',
    otpAuthUrl: value.otpAuthUrl ? value.otpAuthUrl : '',
  }),

  unMap: (value: any) => ({
    id: value._id ? value._id : '',
    first_name: value.firstName ? value.firstName : '',
    last_name: value.lastName ? value.lastName : '',
    mail: value.emailAddress ? value.emailAddress : '',
    contact_phone: value.phoneNumber ? value.phoneNumber : '',
    password: value.password ? value.password : '',
    address1: value.address ? value.address : '',
    city: value.city ? value.city : '',
    state: value.state ? value.state : '',
    country_name: value.countryName ? value.countryName : '',
    post_code: value.postCode ? value.postCode : '',
  }),
};
