/**
 * 0 - REGISTER_NOTIFICATION
 * 1 - FORGOT_PASSWORD_NOTIFICATION
 * 2 - VERIFF_NOTIFICATION
 * 3 - VERIFF_ADDRESS_NOTIFICATION
 * 4 - BANK_NOTIFICATION
 * 5 - VERIFY_CODE_NOTIFICATION
 */
export enum EmailTypes {
  REGISTER_NOTIFICATION,
  FORGOT_PASSWORD_NOTIFICATION,
  VERIFF_NOTIFICATION,
  VERIFF_ADDRESS_NOTIFICATION,
  BANK_NOTIFICATION,
  VERIFY_CODE_NOTIFICATION,
}
